#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jul 12 18:40:20 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=5
shaderPack=
enableShaders=false
