
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1354045
	#The name of the modpack
	modpackName = "Apocalypse Begins [Zombie Apocalypse]"
	#The version of the modpack
	modpackVersion = "3.0.1_P-A_10P-C"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

