! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
! minecraft:dark_forest > minecraft:cherry_grove
! #minecraft:is_forest > minecraft:desert
! #terralith:skylands > null
minecraft:beach > minecraft:plains
minecraft:cherry_grove > minecraft:plains
minecraft:meadow > minecraft:plains
minecraft:mushroom_fields > minecraft:plains
minecraft:sunflower_plains > minecraft:plains
minecraft:flower_forest > minecraft:plains
minecraft:forest > minecraft:plains
minecraft:dark_forest > minecraft:plains
minecraft:birch_forest > minecraft:plains
minecraft:old_growth_birch_forest > minecraft:plains
minecraft:old_growth_pine_taiga > minecraft:plains
minecraft:old_growth_spruce_taiga > minecraft:plains
minecraft:taiga > minecraft:plains
minecraft:swamp > minecraft:plains
minecraft:mangrove_swamp > minecraft:plains
minecraft:windswept_forest > minecraft:snowy_plains
minecraft:windswept_gravelly_hills > minecraft:snowy_plains
minecraft:windswept_hills > minecraft:snowy_plains
minecraft:windswept_savanna > minecraft:snowy_plains
minecraft:snowy_beach > minecraft:snowy_plains
minecraft:snowy_slopes > minecraft:snowy_plains
minecraft:snowy_taiga > minecraft:snowy_plains
minecraft:stony_peaks > minecraft:snowy_plains
minecraft:stony_shore > minecraft:snowy_plains
minecraft:jagged_peaks > minecraft:snowy_plains
minecraft:desert > minecraft:badlands
minecraft:eroded_badlands > minecraft:badlands
minecraft:wooded_badlands > minecraft:badlands
minecraft:jungle > minecraft:badlands
minecraft:sparse_jungle > minecraft:badlands
minecraft:bamboo_jungle > minecraft:badlands
minecraft:savanna > minecraft:badlands
minecraft:savanna_plateau > minecraft:badlands