
#Eatable settings
[eatable]
	#List of items
	#Depending on the mode only these items will be made eatable (WHITELIST) or these items will keep their vanilla behaviour (BLACKLIST)
	#If an item is not affected according to the rules above they will keep their vanilla behaviour
	item_list = [
		"minecraft:apple",
		"minecraft:baked_potato",
		"minecraft:beef",
		"minecraft:beetroot",
		"minecraft:beetroot_soup",
		"minecraft:bread",
		"minecraft:carrot",
		"minecraft:chicken",
		"minecraft:chorus_fruit",
		"minecraft:cod",
		"minecraft:cooked_beef",
		"minecraft:cooked_chicken",
		"minecraft:cooked_cod",
		"minecraft:cooked_mutton",
		"minecraft:cooked_porkchop",
		"minecraft:cooked_rabbit",
		"minecraft:cooked_salmon",
		"minecraft:cookie",
		"minecraft:dried_kelp",
		"minecraft:enchanted_golden_apple",
		"minecraft:glow_berries",
		"minecraft:golden_apple",
		"minecraft:golden_carrot",
		"minecraft:honey_bottle",
		"minecraft:melon_slice",
		"minecraft:mushroom_stew",
		"minecraft:mutton",
		"minecraft:porkchop",
		"minecraft:poisonous_potato",
		"minecraft:potato",
		"minecraft:pufferfish",
		"minecraft:pumpkin_pie",
		"minecraft:rabbit",
		"minecraft:rabbit_stew",
		"minecraft:rotten_flesh",
		"minecraft:salmon",
		"minecraft:spider_eye",
		"minecraft:suspicious_stew",
		"minecraft:sweet_berries",
		"minecraft:tropical_fish",
		"create:bar_of_chocolate",
		"create:chocolate_glazed_berries",
		"create:honeyed_apple",
		"create:sweet_roll",
		"farmersdelight:honey_glazed_ham",
		"farmersdelight:stuffed_pumpkin",
		"farmersdelight:pie_crust",
		"farmersdelight:raw_pasta",
		"farmersdelight:roast_chicken",
		"farmersdelight:cabbage_rolls",
		"farmersdelight:fried_egg",
		"farmersdelight:ham",
		"farmersdelight:shepherds_pie",
		"farmersdelight:apple_pie_slice",
		"farmersdelight:bacon",
		"farmersdelight:bacon_and_eggs",
		"farmersdelight:bacon_sandwich",
		"farmersdelight:baked_cod_stew",
		"farmersdelight:barbecue_stick",
		"farmersdelight:beef_patty",
		"farmersdelight:beef_stew",
		"farmersdelight:bone_broth",
		"farmersdelight:cabbage",
		"farmersdelight:cabbage_leaf",
		"farmersdelight:cake_slice",
		"farmersdelight:chicken_cuts",
		"farmersdelight:chicken_sandwich",
		"farmersdelight:chicken_soup",
		"farmersdelight:chocolate_pie_slice",
		"farmersdelight:cod_roll",
		"farmersdelight:cod_slice",
		"farmersdelight:cooked_bacon",
		"farmersdelight:cooked_chicken_cuts",
		"farmersdelight:cooked_cod_slice",
		"farmersdelight:cooked_mutton_chops",
		"farmersdelight:cooked_rice",
		"farmersdelight:cooked_salmon_slice",
		"farmersdelight:dog_food",
		"farmersdelight:dumplings",
		"farmersdelight:egg_sandwich",
		"farmersdelight:fish_stew",
		"farmersdelight:fried_rice",
		"farmersdelight:fruit_salad",
		"farmersdelight:glow_berry_custard",
		"farmersdelight:grilled_salmon",
		"farmersdelight:hamburger",
		"farmersdelight:honey_cookie",
		"farmersdelight:kelp_roll",
		"farmersdelight:kelp_roll_slice",
		"farmersdelight:melon_popsicle",
		"farmersdelight:minced_beef",
		"farmersdelight:mixed_salad",
		"farmersdelight:mushroom_rice",
		"farmersdelight:mutton_chops",
		"farmersdelight:mutton_wrap",
		"farmersdelight:nether_salad",
		"farmersdelight:noodle_soup",
		"farmersdelight:onion",
		"farmersdelight:pasta_with_meatballs",
		"farmersdelight:pasta_with_mutton_chop",
		"farmersdelight:pumpkin_slice",
		"farmersdelight:pumpkin_soup",
		"farmersdelight:ratatouille",
		"farmersdelight:roasted_mutton_chops",
		"farmersdelight:salmon_roll",
		"farmersdelight:salmon_slice",
		"farmersdelight:smoked_ham",
		"farmersdelight:squid_ink_pasta",
		"farmersdelight:steak_and_potatoes",
		"farmersdelight:stuffed_potato",
		"farmersdelight:sweet_berry_cheesecake_slice",
		"farmersdelight:sweet_berry_cookie",
		"farmersdelight:tomato",
		"farmersdelight:tomato_sauce",
		"farmersdelight:vegetable_noodles",
		"farmersdelight:vegetable_soup",
		"farmersdelight:wheat_dough",
		"refurbished_furniture:bread_slice",
		"refurbished_furniture:cheese",
		"refurbished_furniture:cheese_sandwich",
		"refurbished_furniture:cheese_toastie",
		"refurbished_furniture:glow_berry_jam_toast",
		"refurbished_furniture:meatlovers_pizza_slice",
		"refurbished_furniture:sweet_berry_jam_toast",
		"refurbished_furniture:toast",
		"refurbished_furniture:vegetable_pizza_slice",
		"undead_revamp2:ancientbread",
		"undead_revamp2:clogggerribswithbun",
		"undead_revamp2:cloogerribs"
	]

	#List of items
	#These items will be made uneatable while full (Overrides vanilla behaviour)
	uneatable_list = []
	#Mode as explained in other settings
	#Allowed Values: BLACKLIST, WHITELIST
	mode = "WHITELIST"

