/**
 * Clears all existing loot from a loot table and replaces it with custom loot entries.
 *
 * @param {Internal.LootModificationEventJS} event - The LootJS modifier event.
 * @param {string} lootTable - The resource location of the loot table to modify (e.g. "minecraft:chests/simple_dungeon").
 * @param {Internal.LootEntry[]} lootArray - Array of LootEntry objects to add, typically generated by generateLootArray().
 *
 * @example
 * addLoot(event, "minecraft:chests/simple_dungeon", generateLootArray(generalLoot))
 */
const addLoot = (event, lootTable, lootArray) => {
    const removedLoot = event.addLootTableModifier(lootTable).modifyLoot(Ingredient.all, (itemStack) => {
        itemStack.setCount(0);
        return itemStack;
    });
    removedLoot.addLoot.apply(removedLoot, lootArray);
}

/**
 * Converts a loot definition object into an array of LootEntry objects for use with addLoot().
 * Each item can have multiple count/chance/nbt combinations, each becoming a separate LootEntry.
 *
 * @param {Object} object - Loot definition map where keys are item IDs and values are detail objects.
 * @param {string}   object.<itemId>             - The item's resource location (e.g. "minecraft:iron_sword").
 * @param {number[]} object.<itemId>.counts      - Array of stack sizes, one per loot entry for this item.
 * @param {number[]} object.<itemId>.chances     - Array of drop chances (0.0-1.0), parallel to counts.
 * @param {Object[]} [object.<itemId>.nbts]      - Optional array of NBT objects, parallel to counts. Use null/undefined entries to skip NBT for a specific index.
 *
 * @returns {Internal.LootEntry[]} Flat array of LootEntry objects with randomChance conditions applied.
 *
 * @example
 * const myLoot = {
 *     "minecraft:diamond": { counts: [1, 2], chances: [0.3, 0.1], nbts: [] },
 *     "minecraft:enchanted_book": { counts: [1], chances: [0.05], nbts: [{ StoredEnchantments: [{ id: "minecraft:sharpness", lvl: 3 }] }] }
 * }
 * const entries = generateLootArray(myLoot)
 */
const generateLootArray = (object) => {
    let finalArray = [];
    for (let [id, details] of Object.entries(object)) {
        details["counts"].forEach((count, index) => {
            if (details.nbts && details.nbts[index]) {
                finalArray.push(
                    LootEntry.of(id, count, details["nbts"][index]).when(chance => {
                        chance.randomChance(details["chances"][index])
                    })
                )
            } else {
                finalArray.push(
                    LootEntry.of(id, count).when(chance => {
                        chance.randomChance(details["chances"][index])
                    })
                )
            }
        })
    }
    return finalArray;
}

/**
 * Generates a Minecraft container loot NBT string from a list of item entries.
 *
 * Each entry must be provided in the following format:
 * [itemId, count, slot, nbt]
 *
 * Where:
 * - itemId (string): The item's registry ID (e.g. "minecraft:diamond")
 * - count (number): The stack size
 * - slot (number): The inventory slot index
 * - nbt (string, optional): Additional item NBT without surrounding quotes
 *
 * Example:
 * genLoot(
 *     ["minecraft:diamond", 3, 0],
 *     ["minecraft:iron_sword", 1, 1, "{Damage:10}"]
 * )
 *
 * Returns:
 * {
 *     Items:[
 *         {Slot:0b,id:"minecraft:diamond",Count:3b},
 *         {Slot:1b,id:"minecraft:iron_sword",Count:1b,tag:{Damage:10}}
 *     ]
 * }
 *
 * Useful for generating container block entity NBT such as chests,
 * barrels, shulker boxes, and other inventories.
 *
 * @param {...Array} entries - Item entries in the format [itemId, count, slot, nbt]
 * @returns {string} Container inventory NBT string
 */
function genLoot() {
    var entries = Array.prototype.slice.call(arguments);
    var items = entries.map(function (e) {
        var id = e[0];
        var count = e[1];
        var slot = e[2];
        var nbt = e[3] || null;
        var base = "{Slot:" + slot + "b,id:\"" + id + "\",Count:" + count + "b";
        if (nbt) base += ",tag:" + nbt;
        base += "}";
        return base;
    });
    return "{Items:[" + items.join(",") + "]}";
}

/**
 * Generates writable book NBT using the standard structure expected by
 * Minecraft item NBT and this loot configuration.
 *
 * If author or title are omitted, they default to:
 * - Author: "Unknown"
 * - Title: "Passcodes"
 *
 * Example:
 * generateBookNBT([
 *     "Building 001",
 *     "Barrel Code: 1234",
 *     "Chest Code: 5678"
 * ])
 *
 * @param {string[]} pages - Array of page contents in order.
 * @param {string} author - Book author.
 * @param {string} title - Book title and display name.
 * @returns {Object} Writable book NBT object.
 */
function generateBookNBT(pages, author, title) {
    author = author || "Unknown"
    title = title || "Passcodes"

    return {
        author: author,
        display: {
            Name: `{"text":"${title}"}`
        },
        pages: pages,
        title: title
    }
}

/**
 * Retrieves the keypad code associated with an entry in the
 * KEYPAD_LOOT_TABLE.
 *
 * Example:
 * getCode("building001_barrel")
 *
 * @param {string} name - Keypad loot table entry name.
 * @returns {string|number} The stored keypad code.
 */
function getCode(name) {
    return KEYPAD_LOOT_TABLE[name]["code"]
}

/**
 * Scales all chances in a loot table by a multiplier and returns a new loot table.
 *
 * @param {Object} lootTable - Loot definition map in the format used by generateLootArray().
 * @param {number} float - Positive multiplier to apply to all chance values.
 *
 * @returns {Object} New loot table object with scaled chances. Values are clamped to 1.0.
 *
 * @example
 * amplifyOdds(DYE_LOOT, 2.0)
 */
function amplifyOdds(lootTable, float) {
    var result = {};
    for (var id in lootTable) {
        var entry = lootTable[id];
        result[id] = {
            counts: entry.counts.slice(),
            chances: entry.chances.map(function (chance) {
                return Math.min(chance * float, 1.0);
            }),
            nbts: entry.nbts ? entry.nbts.slice() : []
        };
    }
    return result;
}

//===================================================================
//                          TIERLESS
//===================================================================

const DYE_LOOT = {
    "minecraft:white_dye": { counts: [1, 2, 3], chances: [0.16, 0.08, 0.02], nbts: [] },
    "minecraft:orange_dye": { counts: [1, 2, 3], chances: [0.16, 0.08, 0.02], nbts: [] },
    "minecraft:magenta_dye": { counts: [1, 2, 3], chances: [0.16, 0.08, 0.02], nbts: [] },
    "minecraft:light_blue_dye": { counts: [1, 2, 3], chances: [0.16, 0.08, 0.02], nbts: [] },
    "minecraft:yellow_dye": { counts: [1, 2, 3], chances: [0.16, 0.08, 0.02], nbts: [] },
    "minecraft:lime_dye": { counts: [1, 2, 3], chances: [0.16, 0.08, 0.02], nbts: [] },
    "minecraft:pink_dye": { counts: [1, 2, 3], chances: [0.16, 0.08, 0.02], nbts: [] },
    "minecraft:gray_dye": { counts: [1, 2, 3], chances: [0.16, 0.08, 0.02], nbts: [] },
    "minecraft:light_gray_dye": { counts: [1, 2, 3], chances: [0.16, 0.08, 0.02], nbts: [] },
    "minecraft:cyan_dye": { counts: [1, 2, 3], chances: [0.16, 0.08, 0.02], nbts: [] },
    "minecraft:purple_dye": { counts: [1, 2, 3], chances: [0.16, 0.08, 0.02], nbts: [] },
    "minecraft:blue_dye": { counts: [1, 2, 3], chances: [0.16, 0.08, 0.02], nbts: [] },
    "minecraft:brown_dye": { counts: [1, 2, 3], chances: [0.16, 0.08, 0.02], nbts: [] },
    "minecraft:green_dye": { counts: [1, 2, 3], chances: [0.16, 0.08, 0.02], nbts: [] },
    "minecraft:red_dye": { counts: [1, 2, 3], chances: [0.16, 0.08, 0.02], nbts: [] },
    "minecraft:black_dye": { counts: [1, 2, 3], chances: [0.16, 0.08, 0.02], nbts: [] }
}

const BLOCK_LOOT = {
    "minecraft:oak_log": { counts: [1, 2, 4, 8, 16], chances: [0.2, 0.1, 0.05, 0.02, 0.01], nbts: [] },
    "minecraft:sand": { counts: [1, 2, 4, 8, 16], chances: [0.2, 0.1, 0.05, 0.02, 0.01], nbts: [] },
    "minecraft:cobblestone": { counts: [1, 2, 4, 8, 16], chances: [0.2, 0.1, 0.05, 0.02, 0.01], nbts: [] },
    "minecraft:dirt": { counts: [1, 2, 4, 8, 16], chances: [0.2, 0.1, 0.05, 0.02, 0.01], nbts: [] },
    "minecraft:obsidian": { counts: [1, 2, 4], chances: [0.1, 0.05, 0.01], nbts: [] }
}

const GENERAL_LOOT = {
    "minecraft:stick": { counts: [1, 2, 4], chances: [0.11, 0.055, 0.022], nbts: [] },
    "minecraft:feather": { counts: [1, 2, 4], chances: [0.3, 0.2, 0.1], nbts: [] },
    "minecraft:flint": { counts: [1, 2, 4], chances: [0.11, 0.055, 0.022], nbts: [] },
    "minecraft:string": { counts: [1, 2, 4], chances: [0.11, 0.055, 0.022], nbts: [] },
    "minecraft:clay_ball": { counts: [1, 2, 4], chances: [0.11, 0.055, 0.022], nbts: [] },
    "minecraft:slime_ball": { counts: [1, 2, 4], chances: [0.11, 0.055, 0.022], nbts: [] },
    "minecraft:torch": { counts: [1, 2, 4], chances: [0.11, 0.055, 0.022], nbts: [] },
    "minecraft:paper": { counts: [1, 2, 4], chances: [0.33, 0.22, 0.11], nbts: [] },
    "minecraft:leather": { counts: [1, 2, 4, 8], chances: [0.2, 0.1, 0.05, 0.03], nbts: [] },
    "sophisticatedbackpacks:upgrade_base": { counts: [1], chances: [0.05], nbts: [] },
    "parcool:zipline_rope": { counts: [1, 2, 4], chances: [0.11, 0.055, 0.022], nbts: [] }
}

//===================================================================
//                          TIER 1
//===================================================================

const AMMO_LOOT_T1 = {
    "superbwarfare:taser_electrode": { counts: [1, 2, 4], chances: [0.5, 0.25, 0.12], nbts: [] },
    "superbwarfare:handgun_ammo": { counts: [1, 2, 4], chances: [0.5, 0.25, 0.12], nbts: [] },
    "superbwarfare:shotgun_ammo": { counts: [1, 2, 4], chances: [0.25, 0.1, 0.05], nbts: [] },
    "superbwarfare:rifle_ammo": { counts: [1, 2, 4], chances: [0.4, 0.2, 0.1], nbts: [] },
    "superbwarfare:sniper_ammo": { counts: [1, 2, 4], chances: [0.1, 0.05, 0.02], nbts: [] },
    "superbwarfare:handgun_ammo_box": { counts: [1], chances: [0.1], nbts: [] },
    "superbwarfare:shotgun_ammo_box": { counts: [1], chances: [0.08], nbts: [] },
    "superbwarfare:rifle_ammo_box": { counts: [1], chances: [0.09], nbts: [] },
    "superbwarfare:sniper_ammo_box": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:battery": { counts: [1], chances: [0.05], nbts: [{ "Energy": 50000 }] },
}

const BLUEPRINT_LOOT_T1 = {
    "superbwarfare:glock_17_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:taser_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:marlin_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:mp_443_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:m_1911_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:glock_18_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:mosin_nagant_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:k_98_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:hunting_rifle_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:m_4_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:hk_416_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:ak_12_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:ak_47_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:mp_5_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:qbz_95_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:m_870_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:m_2_hb_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:m_79_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:rpg_blueprint": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:sks_blueprint": { counts: [1], chances: [0.05], nbts: [] }
}

const THROWABLES_LOOT_T1 = {
    "superbwarfare:m18_smoke_grenade": { counts: [1], chances: [0.15], nbts: [] },
    "superbwarfare:hand_grenade": { counts: [1], chances: [0.15], nbts: [] },
    "superbwarfare:claymore_mine": { counts: [1], chances: [0.15], nbts: [] },
    "superbwarfare:edd": { counts: [1], chances: [0.15], nbts: [] },
    "superbwarfare:rgo_grenade": { counts: [1], chances: [0.15], nbts: [] },
    "superbwarfare:detontor": { counts: [1], chances: [0.05], nbts: [] },
    "superbwarfare:c4_bomb": { counts: [1, 1], chances: [0.15, 0.15], nbts: [{ Control: true }, { Control: false }] }
}

const MEDICAL_LOOT_T1 = {
    "marbledsfirstaid:medical_bag": { counts: [1], chances: [0.1], nbts: [] },
    "marbledsfirstaid:medkit": { counts: [1], chances: [0.1], nbts: [] },
    "marbledsfirstaid:first_aid_kit": { counts: [1], chances: [0.1], nbts: [] },
    "marbledsfirstaid:bandaid_box": { counts: [1], chances: [0.1], nbts: [] },
    "marbledsfirstaid:bandages": { counts: [1, 2, 4, 6], chances: [0.5, 0.4, 0.3, 0.1], nbts: [] },
    "marbledsfirstaid:bandaid": { counts: [1, 2, 4, 6], chances: [0.7, 0.4, 0.3, 0.1], nbts: [] },
    "marbledsfirstaid:panacea_pills": { counts: [1], chances: [0.1], nbts: [] },
    "marbledsfirstaid:curative_pills": { counts: [1], chances: [0.1], nbts: [] },
    "marbledsfirstaid:pain_pills": { counts: [1], chances: [0.1], nbts: [] },
    "marbledsfirstaid:eye_drops": { counts: [1], chances: [0.1], nbts: [] },
    "marbledsfirstaid:antidote": { counts: [1], chances: [0.1], nbts: [] },
    "marbledsfirstaid:tonic": { counts: [1], chances: [0.1], nbts: [] },
    "marbledsfirstaid:elixir": { counts: [1], chances: [0.1], nbts: [] },
    "marbledsfirstaid:morphine": { counts: [1], chances: [0.1], nbts: [] },
    "marbledsfirstaid:stimpack": { counts: [1], chances: [0.1], nbts: [] },
    "marbledsfirstaid:morphine_syringe": { counts: [1], chances: [0.1], nbts: [] },
    "marbledsfirstaid:adrenaline_syringe": { counts: [1], chances: [0.1], nbts: [] }
}

const ENCHANTMENTS_LOOT_T1 = {
    "minecraft:enchanted_book": {
        counts: Array(24).fill(1), chances: Array(24).fill(0.05), nbts: [
            { StoredEnchantments: [{ id: "minecraft:protection", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:fire_protection", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:feather_falling", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:blast_protection", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:projectile_protection", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:respiration", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:aqua_affinity", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:thorns", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:depth_strider", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:frost_walker", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:soul_speed", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:swift_sneak", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:sharpness", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:knockback", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:fire_aspect", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:looting", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:sweeping", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:efficiency", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:silk_touch", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:unbreaking", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:fortune", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:luck_of_the_sea", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:lure", lvl: 1 }] },
            { StoredEnchantments: [{ id: "minecraft:mending", lvl: 1 }] }
        ]
    }
}

const INGOT_LOOT_T1 = {
    "minecraft:iron_nugget": { counts: [1, 2, 4, 8], chances: [0.2, 0.1, 0.05, 0.03], nbts: [] },
    "minecraft:gold_nugget": { counts: [1, 2, 4, 8], chances: [0.2, 0.1, 0.05, 0.03], nbts: [] },
    "mekanism:nugget_steel": { counts: [1, 2, 4, 8], chances: [0.2, 0.1, 0.05, 0.03], nbts: [] },
    "mekanism:nugget_osmium": { counts: [1, 2, 4, 8], chances: [0.2, 0.1, 0.05, 0.03], nbts: [] },
    "mekanism:dirty_dust_iron": { counts: [1, 2, 4, 8], chances: [0.2, 0.1, 0.05, 0.03], nbts: [] },
    "mekanism:dirty_dust_gold": { counts: [1, 2, 4, 8], chances: [0.2, 0.1, 0.05, 0.03], nbts: [] },
    "mekanism:dirty_dust_osmium": { counts: [1, 2, 4, 8], chances: [0.2, 0.1, 0.05, 0.03], nbts: [] },
    "mekanism:dirty_dust_copper": { counts: [1, 2, 4, 8], chances: [0.2, 0.1, 0.05, 0.03], nbts: [] },
    "mekanism:dust_steel": { counts: [1, 2, 4, 8], chances: [0.2, 0.1, 0.05, 0.03], nbts: [] },
    "mekanism:dust_charcoal": { counts: [1, 2, 4, 8], chances: [0.2, 0.1, 0.05, 0.03], nbts: [] },
    "mekanism:dust_coal": { counts: [1, 2, 4, 8], chances: [0.2, 0.1, 0.05, 0.03], nbts: [] },
    "minecraft:redstone": { counts: [1, 2, 4, 8], chances: [0.2, 0.1, 0.05, 0.03], nbts: [] }
}

const MONEY_LOOT_T1 = {
    "saros__money_mod:cent_1": { counts: [1, 2, 3], chances: [0.08, 0.04, 0.02], nbts: [] },
    "saros__money_mod:cent_2": { counts: [1, 2, 3], chances: [0.07, 0.03, 0.015], nbts: [] },
    "saros__money_mod:cent_5": { counts: [1, 2, 3], chances: [0.06, 0.03, 0.012], nbts: [] },
    "saros__money_mod:cent_10": { counts: [1, 2, 3], chances: [0.05, 0.025, 0.01], nbts: [] },
    "saros__money_mod:cent_20": { counts: [1, 2, 3], chances: [0.04, 0.02, 0.008], nbts: [] },
    "saros__money_mod:cent_50": { counts: [1, 2, 3], chances: [0.03, 0.015, 0.006], nbts: [] },
    "saros__money_mod:euro_1": { counts: [1, 2, 3], chances: [0.025, 0.012, 0.005], nbts: [] },
    "saros__money_mod:euro_2": { counts: [1, 2, 3], chances: [0.02, 0.01, 0.004], nbts: [] },
    "saros__money_mod:euro_5": { counts: [1, 2, 3], chances: [0.015, 0.007, 0.003], nbts: [] },
    "saros__money_mod:euro_10": { counts: [1, 2, 3], chances: [0.01, 0.005, 0.002], nbts: [] },
    "saros__money_mod:euro_20": { counts: [1, 2, 3], chances: [0.007, 0.003, 0.001], nbts: [] },
    "saros__money_mod:euro_50": { counts: [1, 2, 3], chances: [0.005, 0.002, 0.0008], nbts: [] },
    "saros__money_mod:euro_100": { counts: [1, 2, 3], chances: [0.003, 0.001, 0.0005], nbts: [] },
    "saros__money_mod:euro_200": { counts: [1, 2, 3], chances: [0.002, 0.0008, 0.0003], nbts: [] },
    "saros__money_mod:euro_500": { counts: [1, 2, 3], chances: [0.001, 0.0004, 0.0001], nbts: [] },
}

const FLARE_LOOT_T1 = {
    "dyairdrop:flaregun1": { counts: [1], chances: [0.2], nbts: [] },
    "dyairdrop:flaregun2": { counts: [1], chances: [0.2], nbts: [] },
    "dyairdrop:flaregun3": { counts: [1], chances: [0.2], nbts: [] },
    "dyairdrop:flaregun4": { counts: [1], chances: [0.2], nbts: [] },
    "dyairdrop:flaregun5": { counts: [1], chances: [0.2], nbts: [] }
}

const SEED_LOOT_T1 = {
    "minecraft:wheat_seeds": { counts: [1, 2, 3], chances: [0.5, 0.25, 0.125], nbts: [] },
    "minecraft:pumpkin_seeds": { counts: [1, 2, 3], chances: [0.5, 0.25, 0.125], nbts: [] },
    "minecraft:melon_seeds": { counts: [1, 2, 3], chances: [0.5, 0.25, 0.125], nbts: [] },
    "minecraft:beetroot_seeds": { counts: [1, 2, 3], chances: [0.5, 0.25, 0.125], nbts: [] },
    "farmersdelight:cabbage_seeds": { counts: [1, 2, 3], chances: [0.5, 0.25, 0.125], nbts: [] },
    "farmersdelight:tomato_seeds": { counts: [1, 2, 3], chances: [0.5, 0.25, 0.125], nbts: [] },
    "minecraft:cocoa_beans": { counts: [1, 2, 3], chances: [0.5, 0.25, 0.125], nbts: [] }
}

const FOOD_LOOT_T1 = {
    "minecraft:apple": { counts: [1], chances: [0.21], nbts: [] },
    "minecraft:baked_potato": { counts: [1], chances: [0.15], nbts: [] },
    "minecraft:beef": { counts: [1], chances: [0.25], nbts: [] },
    "minecraft:beetroot": { counts: [1], chances: [0.25], nbts: [] },
    "minecraft:beetroot_soup": { counts: [1], chances: [0.08], nbts: [] },
    "minecraft:bread": { counts: [1], chances: [0.18], nbts: [] },
    "minecraft:carrot": { counts: [1], chances: [0.25], nbts: [] },
    "minecraft:chicken": { counts: [1], chances: [0.25], nbts: [] },
    "minecraft:cod": { counts: [1], chances: [0.25], nbts: [] },
    "minecraft:cooked_beef": { counts: [1], chances: [0.11], nbts: [] },
    "minecraft:cooked_chicken": { counts: [1], chances: [0.13], nbts: [] },
    "minecraft:cooked_cod": { counts: [1], chances: [0.15], nbts: [] },
    "minecraft:cooked_mutton": { counts: [1], chances: [0.12], nbts: [] },
    "minecraft:cooked_porkchop": { counts: [1], chances: [0.11], nbts: [] },
    "minecraft:cooked_rabbit": { counts: [1], chances: [0.15], nbts: [] },
    "minecraft:cooked_salmon": { counts: [1], chances: [0.12], nbts: [] },
    "minecraft:cookie": { counts: [1], chances: [0.22], nbts: [] },
    "minecraft:dried_kelp": { counts: [1], chances: [0.25], nbts: [] },
    "minecraft:glow_berries": { counts: [1], chances: [0.24], nbts: [] },
    "minecraft:honey_bottle": { counts: [1], chances: [0.19], nbts: [] },
    "minecraft:melon_slice": { counts: [1], chances: [0.24], nbts: [] },
    "minecraft:mushroom_stew": { counts: [1], chances: [0.08], nbts: [] },
    "minecraft:mutton": { counts: [1], chances: [0.25], nbts: [] },
    "minecraft:porkchop": { counts: [1], chances: [0.25], nbts: [] },
    "minecraft:potato": { counts: [1], chances: [0.25], nbts: [] },
    "minecraft:pumpkin_pie": { counts: [1], chances: [0.03], nbts: [] },
    "minecraft:rabbit": { counts: [1], chances: [0.25], nbts: [] },
    "minecraft:rabbit_stew": { counts: [1], chances: [0.05], nbts: [] },
    "minecraft:salmon": { counts: [1], chances: [0.25], nbts: [] },
    "minecraft:sweet_berries": { counts: [1], chances: [0.24], nbts: [] },
    "minecraft:tropical_fish": { counts: [1], chances: [0.25], nbts: [] },
    "farmersdelight:apple_cider": { counts: [1], chances: [0.10], nbts: [] },
    "farmersdelight:apple_pie": { counts: [1], chances: [0.02], nbts: [] },
    "farmersdelight:apple_pie_slice": { counts: [1], chances: [0.08], nbts: [] },
    "farmersdelight:bacon": { counts: [1], chances: [0.25], nbts: [] },
    "farmersdelight:bacon_and_eggs": { counts: [1], chances: [0.01], nbts: [] },
    "farmersdelight:bacon_sandwich": { counts: [1], chances: [0.03], nbts: [] },
    "farmersdelight:baked_cod_stew": { counts: [1], chances: [0.02], nbts: [] },
    "farmersdelight:barbecue_stick": { counts: [1], chances: [0.05], nbts: [] },
    "farmersdelight:beef_patty": { counts: [1], chances: [0.15], nbts: [] },
    "farmersdelight:beef_stew": { counts: [1], chances: [0.02], nbts: [] },
    "farmersdelight:bone_broth": { counts: [1], chances: [0.07], nbts: [] },
    "farmersdelight:cabbage": { counts: [1], chances: [0.25], nbts: [] },
    "farmersdelight:cabbage_leaf": { counts: [1], chances: [0.25], nbts: [] },
    "farmersdelight:cabbage_rolls": { counts: [1], chances: [0.04], nbts: [] },
    "farmersdelight:cake_slice": { counts: [1], chances: [0.12], nbts: [] },
    "farmersdelight:chicken_cuts": { counts: [1], chances: [0.25], nbts: [] },
    "farmersdelight:chicken_sandwich": { counts: [1], chances: [0.03], nbts: [] },
    "farmersdelight:chicken_soup": { counts: [1], chances: [0.02], nbts: [] },
    "farmersdelight:chocolate_pie": { counts: [1], chances: [0.015], nbts: [] },
    "farmersdelight:chocolate_pie_slice": { counts: [1], chances: [0.08], nbts: [] },
    "farmersdelight:cod_roll": { counts: [1], chances: [0.05], nbts: [] },
    "farmersdelight:cod_slice": { counts: [1], chances: [0.25], nbts: [] },
    "farmersdelight:cooked_bacon": { counts: [1], chances: [0.14], nbts: [] },
    "farmersdelight:cooked_chicken_cuts": { counts: [1], chances: [0.16], nbts: [] },
    "farmersdelight:cooked_cod_slice": { counts: [1], chances: [0.17], nbts: [] },
    "farmersdelight:cooked_mutton_chops": { counts: [1], chances: [0.15], nbts: [] },
    "farmersdelight:cooked_rice": { counts: [1], chances: [0.16], nbts: [] },
    "farmersdelight:cooked_salmon_slice": { counts: [1], chances: [0.15], nbts: [] },
    "farmersdelight:dog_food": { counts: [1], chances: [0.18], nbts: [] },
    "farmersdelight:dumplings": { counts: [1], chances: [0.04], nbts: [] },
    "farmersdelight:egg_sandwich": { counts: [1], chances: [0.03], nbts: [] },
    "farmersdelight:fried_egg": { counts: [1], chances: [0.14], nbts: [] },
    "farmersdelight:fried_rice": { counts: [1], chances: [0.03], nbts: [] },
    "farmersdelight:fruit_salad": { counts: [1], chances: [0.05], nbts: [] },
    "farmersdelight:gleaming_salad": { counts: [1], chances: [0.02], nbts: [] },
    "farmersdelight:glow_berry_custard": { counts: [1], chances: [0.04], nbts: [] },
    "farmersdelight:grilled_salmon": { counts: [1], chances: [0.03], nbts: [] },
    "farmersdelight:ham": { counts: [1], chances: [0.10], nbts: [] },
    "farmersdelight:hamburger": { counts: [1], chances: [0.02], nbts: [] },
    "farmersdelight:honey_cookie": { counts: [1], chances: [0.16], nbts: [] },
    "farmersdelight:honey_glazed_ham": { counts: [1], chances: [0.01], nbts: [] },
    "farmersdelight:hot_cocoa": { counts: [1], chances: [0.08], nbts: [] },
    "farmersdelight:kelp_roll": { counts: [1], chances: [0.05], nbts: [] },
    "farmersdelight:kelp_roll_slice": { counts: [1], chances: [0.10], nbts: [] },
    "farmersdelight:melon_juice": { counts: [1], chances: [0.12], nbts: [] },
    "farmersdelight:melon_popsicle": { counts: [1], chances: [0.09], nbts: [] },
    "farmersdelight:milk_bottle": { counts: [1], chances: [0.20], nbts: [] },
    "farmersdelight:minced_beef": { counts: [1], chances: [0.25], nbts: [] },
    "farmersdelight:mixed_salad": { counts: [1], chances: [0.02], nbts: [] },
    "farmersdelight:mushroom_rice": { counts: [1], chances: [0.03], nbts: [] },
    "farmersdelight:mutton_chops": { counts: [1], chances: [0.25], nbts: [] },
    "farmersdelight:mutton_wrap": { counts: [1], chances: [0.03], nbts: [] },
    "farmersdelight:nether_salad": { counts: [1], chances: [0.06], nbts: [] },
    "farmersdelight:noodle_soup": { counts: [1], chances: [0.03], nbts: [] },
    "farmersdelight:onion": { counts: [1], chances: [0.25], nbts: [] },
    "farmersdelight:onion_soup": { counts: [1], chances: [0.07], nbts: [] },
    "farmersdelight:pasta_with_meatballs": { counts: [1], chances: [0.02], nbts: [] },
    "farmersdelight:pasta_with_mutton_chop": { counts: [1], chances: [0.02], nbts: [] },
    "farmersdelight:pie_crust": { counts: [1], chances: [0.25], nbts: [] },
    "farmersdelight:pumpkin_slice": { counts: [1], chances: [0.23], nbts: [] },
    "farmersdelight:pumpkin_soup": { counts: [1], chances: [0.02], nbts: [] },
    "farmersdelight:ratatouille": { counts: [1], chances: [0.001], nbts: [] },
    "farmersdelight:raw_pasta": { counts: [1], chances: [0.24], nbts: [] },
    "farmersdelight:roast_chicken": { counts: [1], chances: [0.01], nbts: [] },
    "farmersdelight:roasted_mutton_chops": { counts: [1], chances: [0.02], nbts: [] },
    "farmersdelight:salmon_roll": { counts: [1], chances: [0.05], nbts: [] },
    "farmersdelight:salmon_slice": { counts: [1], chances: [0.25], nbts: [] },
    "farmersdelight:shepherds_pie": { counts: [1], chances: [0.01], nbts: [] },
    "farmersdelight:smoked_ham": { counts: [1], chances: [0.001], nbts: [] },
    "farmersdelight:squid_ink_pasta": { counts: [1], chances: [0.02], nbts: [] },
    "farmersdelight:steak_and_potatoes": { counts: [1], chances: [0.02], nbts: [] },
    "farmersdelight:stuffed_potato": { counts: [1], chances: [0.04], nbts: [] },
    "farmersdelight:sweet_berry_cheesecake": { counts: [1], chances: [0.02], nbts: [] },
    "farmersdelight:sweet_berry_cheesecake_slice": { counts: [1], chances: [0.08], nbts: [] },
    "farmersdelight:sweet_berry_cookie": { counts: [1], chances: [0.16], nbts: [] },
    "farmersdelight:tomato": { counts: [1], chances: [0.25], nbts: [] },
    "farmersdelight:tomato_sauce": { counts: [1], chances: [0.09], nbts: [] },
    "farmersdelight:vegetable_noodles": { counts: [1], chances: [0.01], nbts: [] },
    "farmersdelight:vegetable_soup": { counts: [1], chances: [0.001], nbts: [] },
    "farmersdelight:wheat_dough": { counts: [1], chances: [0.25], nbts: [] },
    "farmersdelight:stuffed_pumpkin": { counts: [1], chances: [0.01], nbts: [] },
    "farmersdelight:fish_stew": { counts: [1], chances: [0.02], nbts: [] }
}

const GUN_LOOT_T1 = {
    "superbwarfare:glock_17": { counts: [1], chances: [0.45], nbts: [] },
    "superbwarfare:taser": { counts: [1], chances: [0.35], nbts: [] },
    "superbwarfare:marlin": { counts: [1], chances: [0.38], nbts: [] },
    "superbwarfare:mp_443": { counts: [1], chances: [0.40], nbts: [] },
    "superbwarfare:m_1911": { counts: [1], chances: [0.42], nbts: [] },
    "superbwarfare:glock_18": { counts: [1], chances: [0.28], nbts: [] },
    "superbwarfare:mosin_nagant": { counts: [1], chances: [0.12], nbts: [] },
    "superbwarfare:k_98": { counts: [1], chances: [0.10], nbts: [] },
    "superbwarfare:hunting_rifle": { counts: [1], chances: [0.09], nbts: [] },
    "superbwarfare:sks": { counts: [1], chances: [0.13], nbts: [] },
    "superbwarfare:m_4": { counts: [1], chances: [0.20], nbts: [] },
    "superbwarfare:hk_416": { counts: [1], chances: [0.18], nbts: [] },
    "superbwarfare:ak_12": { counts: [1], chances: [0.16], nbts: [] },
    "superbwarfare:ak_47": { counts: [1], chances: [0.17], nbts: [] },
    "superbwarfare:qbz_95": { counts: [1], chances: [0.15], nbts: [] },
    "superbwarfare:mp_5": { counts: [1], chances: [0.25], nbts: [] },
    "superbwarfare:m_870": { counts: [1], chances: [0.22], nbts: [] },
    "superbwarfare:m_2_hb": { counts: [1], chances: [0.18], nbts: [] },
    "superbwarfare:m_79": { counts: [1], chances: [0.06], nbts: [] },
    "superbwarfare:rpg": { counts: [1], chances: [0.01], nbts: [] }
}

// Air Drops
const LARGE_AIR_DROP = Object.assign({}, GENERAL_LOOT, BLOCK_LOOT, amplifyOdds(MONEY_LOOT_T1, 1.5), amplifyOdds(DYE_LOOT, 0.5), ENCHANTMENTS_LOOT_T1)
const SMALL_AIR_DROP = Object.assign({}, GENERAL_LOOT, amplifyOdds(BLOCK_LOOT, 1.5), MONEY_LOOT_T1, amplifyOdds(DYE_LOOT, 0.5))
const MEDICAL_AIR_DROP = Object.assign({}, amplifyOdds(MEDICAL_LOOT_T1, 1.5), amplifyOdds(FOOD_LOOT_T1, 0.5))
const WEAPON_AIR_DROP = Object.assign({}, AMMO_LOOT_T1, BLUEPRINT_LOOT_T1, THROWABLES_LOOT_T1, GUN_LOOT_T1)


// Security Related Loot Tables
const KEYPAD_LOOT_TABLE = {
    "building001_barrel": {
        loot: genLoot(
            ["superbwarfare:handgun_ammo", 64, 0],
            ["minecraft:iron_ingot", 4, 1],
            ["saros__money_mod:euro_100", 1, 2]
        ),
        code: "3013"
    },
    "building001_chest": {
        loot: genLoot(
            ["superbwarfare:rifle_ammo", 64, 0],
            ["minecraft:gold_ingot", 4, 1],
            ["saros__money_mod:euro_200", 1, 2]
        ),
        code: "23413"
    },
    "building002_chest": {
        loot: genLoot(
            ["superbwarfare:shotgun_ammo", 64, 0],
            ["minecraft:iron_ingot", 4, 1],
            ["saros__money_mod:euro_100", 1, 2]
        ),
        code: "041"
    },
    "building003_chest1": {
        loot: genLoot(
            ["superbwarfare:sniper_ammo", 64, 0],
            ["minecraft:iron_ingot", 4, 1],
            ["saros__money_mod:euro_100", 1, 2]
        ),
        code: "71592"
    },
    "building003_chest2": {
        loot: genLoot(
            ["superbwarfare:heavy_ammo", 16, 0],
            ["minecraft:gold_ingot", 4, 1],
            ["saros__money_mod:euro_200", 1, 2]
        ),
        code: "9142"
    },
    "building004_chest": {
        loot: genLoot(
            ["superbwarfare:handgun_ammo", 64, 0],
            ["minecraft:iron_ingot", 4, 1],
            ["saros__money_mod:euro_100", 1, 2]
        ),
        code: "3512"
    },
    "building004_barrel": {
        loot: genLoot(
            ["superbwarfare:handgun_ammo", 64, 0],
            ["minecraft:gold_ingot", 4, 1],
            ["saros__money_mod:euro_100", 1, 2]
        ),
        code: "62348"
    },
    "building004_display_case": {
        loot: "{DisplayedStack:{RCount:1,id:'superbwarfare:glock_17',Count: 1}}",
        code: "826931"
    },
    "building004_door": {
        loot: "{}",
        code: "591368"
    },
    "building005_barrel": {
        loot: genLoot(
            ["superbwarfare:handgun_ammo", 64, 0],
            ["minecraft:gold_ingot", 4, 1],
            ["saros__money_mod:euro_100", 1, 2]
        ),
        code: "1358393"
    },
    "building005_keypad": {
        loot: "{}",
        code: "158206"
    },
    "building006_chest": {
        loot: genLoot(
            ["superbwarfare:heavy_ammo", 64, 0],
            ["saros__money_mod:euro_50", 1, 1]
        ),
        code: "9183064"
    },
    "building007_chest": {
        loot: genLoot(
            ["superbwarfare:ammo_box", 1, 0, "{HeavyAmmo:200,ShotgunAmmo:300,HandgunAmmo:500,SniperAmmo:250,RifleAmmo:400}"]
        ),
        code: "31415623194"
    },
}

const KEYCARD_LOOT_TABLE = {
    "building004_doors": {
        "signature": 4,
        "acceptedLevels": "{lvl1:true}"
    },
    "building005_vault": {
        "signature": 5,
        "acceptedLevels": "{lvl1:true}"
    }
}

// Office
const BUILDING_001_ROOF = {
    "minecraft:writable_book": { counts: [1], chances: [1.0], nbts: [generateBookNBT(["Building 001", `Barrel Code: ${getCode("building001_barrel")}`, `Chest Code: ${getCode("building001_chest")}`])] },
    "saros__money_mod:euro_50": { counts: [1], chances: [1.0], nbts: [] }
}

// Apartment
const BUILDING_002_ROOF = {
    "minecraft:writable_book": { counts: [1], chances: [1.0], nbts: [generateBookNBT(["Building 002", `Chest Code: ${getCode("building002_chest")}`])] },
    "saros__money_mod:euro_10": { counts: [1], chances: [1.0], nbts: [] }
}

// Library
const BUILDING_003_ROOF = {
    "minecraft:writable_book": { counts: [1], chances: [1.0], nbts: [generateBookNBT(["Building 003", `Ground Floor Chest Code: ${getCode("building003_chest1")}`, `Top Floor Chest Code: ${getCode("building003_chest2")}`])] },
    "saros__money_mod:euro_10": { counts: [1], chances: [1.0], nbts: [] }
}

// Police Station
const BUILDING_004_ROOF = {
    "securitycraft:keycard_lv1": { counts: [1], chances: [1.0], nbts: [{ "ownerName": "owner", "ownerUUID": "ownerUUID", "linked": true, "signature": KEYCARD_LOOT_TABLE["building004_doors"]["signature"] }] }
}
const BUILDING_004_PRISON = {
    "minecraft:writable_book": { counts: [1], chances: [0.15], nbts: [generateBookNBT(["Building 004", `Secret Chest Code: ${getCode("building004_chest")}`, `Secret Barrel Code: ${getCode("building004_barrel")}`, `Door Code: ${getCode("building004_door")}`, `Case Code: ${getCode("building004_display_case")}`])] },
}

//Bank
const BUILDING_005_ROOF = {
    "minecraft:writable_book": { counts: [1], chances: [1.0], nbts: [generateBookNBT(["Building 005", `Barrel Code: ${getCode("building005_barrel")}`, `Vault Code: ${getCode("building005_keypad")}`])] },
}
const BUILDING_005_VAULT = {
    "saros__money_mod:euro_1": { counts: [1], chances: [0.50], nbts: [] },
    "saros__money_mod:euro_2": { counts: [1], chances: [0.35], nbts: [] },
    "saros__money_mod:euro_5": { counts: [1], chances: [0.25], nbts: [] },
    "saros__money_mod:euro_10": { counts: [1], chances: [0.18], nbts: [] },
    "saros__money_mod:euro_20": { counts: [1], chances: [0.12], nbts: [] },
    "saros__money_mod:euro_50": { counts: [1], chances: [0.08], nbts: [] },
    "saros__money_mod:euro_100": { counts: [1], chances: [0.05], nbts: [] },
    "saros__money_mod:euro_200": { counts: [1], chances: [0.03], nbts: [] },
    "saros__money_mod:euro_500": { counts: [1], chances: [0.015], nbts: [] }
}

const LOOT_TABLES = {
    "abza:building001/general": Object.assign({}, GENERAL_LOOT, BLOCK_LOOT, MONEY_LOOT_T1),
    "abza:building001/codes": Object.assign({}, BUILDING_001_ROOF),

    "abza:building002/general": Object.assign({}, GENERAL_LOOT, BLOCK_LOOT),
    "abza:building002/laundry": Object.assign({}, GENERAL_LOOT, BLOCK_LOOT, DYE_LOOT),
    "abza:building002/codes": Object.assign({}, MONEY_LOOT_T1, BUILDING_002_ROOF, DYE_LOOT),

    "abza:general/kitchen": Object.assign({}, amplifyOdds(FOOD_LOOT_T1, 0.2)),

    "abza:building003/general": Object.assign({}, GENERAL_LOOT, BLOCK_LOOT, ENCHANTMENTS_LOOT_T1),
    "abza:building003/codes": Object.assign({}, MONEY_LOOT_T1, BUILDING_003_ROOF, ENCHANTMENTS_LOOT_T1),

    "abza:building004/general": Object.assign({}, GENERAL_LOOT, AMMO_LOOT_T1, BLOCK_LOOT, BUILDING_004_PRISON),
    "abza:building004/codes": Object.assign({}, MONEY_LOOT_T1, BUILDING_004_ROOF, AMMO_LOOT_T1, BUILDING_004_PRISON),
    "abza:building004/weapons": Object.assign({}, MONEY_LOOT_T1, THROWABLES_LOOT_T1, AMMO_LOOT_T1, amplifyOdds(FLARE_LOOT_T1, 0.3)),

    "abza:building005/general": Object.assign({}, GENERAL_LOOT, BLOCK_LOOT, MONEY_LOOT_T1),
    "abza:building005/codes": Object.assign({}, amplifyOdds(MONEY_LOOT_T1, 3.0), BUILDING_005_ROOF),
    "abza:building005/vault": Object.assign({}, BUILDING_005_VAULT, GENERAL_LOOT, BLOCK_LOOT, INGOT_LOOT_T1, amplifyOdds(FLARE_LOOT_T1, 0.1)),

    "abza:building006/general": Object.assign({}, GENERAL_LOOT, BLOCK_LOOT, MEDICAL_LOOT_T1),
    "abza:building006/roof": Object.assign({}, MONEY_LOOT_T1, amplifyOdds(MEDICAL_LOOT_T1, 3.0)),

    "abza:building007/general": Object.assign({}, GENERAL_LOOT, BLOCK_LOOT, DYE_LOOT, MONEY_LOOT_T1, SEED_LOOT_T1, amplifyOdds(GUN_LOOT_T1, 0.1), amplifyOdds(AMMO_LOOT_T1, 0.1), amplifyOdds(FOOD_LOOT_T1, 0.1)),

    "dyairdrop:chests/largeairdrop1": Object.assign({}, LARGE_AIR_DROP),
    "dyairdrop:chests/largeairdrop2": Object.assign({}, amplifyOdds(LARGE_AIR_DROP, 1.2)),
    "dyairdrop:chests/largeairdrop3": Object.assign({}, amplifyOdds(LARGE_AIR_DROP, 1.4)),
    "dyairdrop:chests/largeairdrop4": Object.assign({}, amplifyOdds(LARGE_AIR_DROP, 1.6)),
    "dyairdrop:chests/largeairdrop5": Object.assign({}, amplifyOdds(LARGE_AIR_DROP, 1.8)),
    "dyairdrop:chests/medicalairdrop1": Object.assign({}, MEDICAL_AIR_DROP),
    "dyairdrop:chests/medicalairdrop2": Object.assign({}, amplifyOdds(MEDICAL_AIR_DROP, 1.2)),
    "dyairdrop:chests/medicalairdrop3": Object.assign({}, amplifyOdds(MEDICAL_AIR_DROP, 1.4)),
    "dyairdrop:chests/medicalairdrop4": Object.assign({}, amplifyOdds(MEDICAL_AIR_DROP, 1.6)),
    "dyairdrop:chests/medicalairdrop5": Object.assign({}, amplifyOdds(MEDICAL_AIR_DROP, 1.8)),
    "dyairdrop:chests/smallairdrop1": Object.assign({}, SMALL_AIR_DROP),
    "dyairdrop:chests/smallairdrop2": Object.assign({}, amplifyOdds(SMALL_AIR_DROP, 1.2)),
    "dyairdrop:chests/smallairdrop3": Object.assign({}, amplifyOdds(SMALL_AIR_DROP, 1.4)),
    "dyairdrop:chests/smallairdrop4": Object.assign({}, amplifyOdds(SMALL_AIR_DROP, 1.6)),
    "dyairdrop:chests/smallairdrop5": Object.assign({}, amplifyOdds(SMALL_AIR_DROP, 1.8)),
    "dyairdrop:chests/weaponairdrop1": Object.assign({}, WEAPON_AIR_DROP),
    "dyairdrop:chests/weaponairdrop2": Object.assign({}, amplifyOdds(WEAPON_AIR_DROP, 1.2)),
    "dyairdrop:chests/weaponairdrop3": Object.assign({}, amplifyOdds(WEAPON_AIR_DROP, 1.4)),
    "dyairdrop:chests/weaponairdrop4": Object.assign({}, amplifyOdds(WEAPON_AIR_DROP, 1.6)),
    "dyairdrop:chests/weaponairdrop5": Object.assign({}, amplifyOdds(WEAPON_AIR_DROP, 1.8)),

}

LootJS.modifiers(event => {
    for (let [lootTable, details] of Object.entries(LOOT_TABLES)) {
        addLoot(event, lootTable, generateLootArray(details));
    }
})